### ISSUE TITLE
Source map error in console

### ISSUE THREAD

**Issue by ethus3h** [hyperfekt/webextension-remove-redirect#10]
### New Issue Checklist (tick off like this: `[x]`)

- `[yes ]` I checked existing issues (open and closed) for possible duplicates
- `[yes v58.0 ]` I can reproduce the problem on the latest stable version (not nightly!)
- `[yes ]` The issue is not about adding entries to the default blacklist

### What is your browser?

- `[yes ]` Firefox
- `[no ]` Chrome

### What is your operating system?

- `[yes ]` Linux
- `[no ]` Mac
- `[no ]` Windows

### Description (please include examples/screenshots where applicable)

The add-on places an error into the Web console for every Web page I tested. This gets in the way of using the Web console while the add-on is enabled.

Here is the text of the error:
```Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://b3c66796-33e4-4cac-b872-ebcabcda9b8d/browser-polyfill.js
Source Map URL: browser-polyfill.js.map
```
Screen shot: 
![screenshot_2018 03 09_00 23 57](https://user-images.githubusercontent.com/10457522/37191922-84d762f4-2330-11e8-967b-1c5a8cf888ab.png)

**Comment by hyperfekt** [comment]
Strangely I am unable to reproduce this (sorry for the delayed answer, the notification must have gone under) - I specifically checked that I had source maps enabled. Can you confirm that this issue is still occuring?

**Comment by ethus3h** [comment]
Yay, I've tested and the issue is indeed gone. Thank you! :)
