### ISSUE TITLE
noob and confused

### ISSUE THREAD

**Issue by Trueffel** [hyperfekt/webextension-remove-redirect#13]
I hope this is ok here, but im dont know where else to go. I don't understand how this works and the match pattern link goes way over my head 

The url's i need modified add a word at the end like "related". I've put the word on the whitelist, but it doesn't do anything to the url's

I know i'm stupid, but can someone tell me what i'm doing wrong? (firefox win7)

**Comment by hyperfekt** [comment]
If you want to exclude a URL pattern from algorithm you will have to add a matching regular expression (Javascript style) to the blacklist (to include one do the same but add it to the whitelist instead).
Ignore the match patterns, they are only relevant in the extension this one is forked from.
Here is a short guide: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions
Here is a tool to test yours out (make sure to change to Javascript): https://regex101.com
For example if you want to match any URL ending with "related", you would enter `(.*)related`.
The most important things you need to know is to escape dots with backslash, and use the (.*) pattern to match any string in that location.
