### ISSUE TITLE
Silly question

### ISSUE THREAD

**Issue by EstherMoellman** [hyperfekt/webextension-remove-redirect#14]
Sorry for my silly question: I can't understand the difference between Skip Redirect and Remove Redirect. I read the description with the comparison. I am sorry, I still don't understand.

Please, could you explain in simple words what is the benefit of this add-on, when compared to Skip Redirect? Does RR work better? Does block more stuff? Is it faster? Less CPU? Better browser performing? Etc?

Thank you and feel free to close my issue.

**Comment by hyperfekt** [comment]
In the most simple terms, Remove Redirect attempts to change the links on the page to their final destination, while Skip Redirect tries to change the network requests.
The result is that Remove Redirect can show you where links lead and make them easy to copy & paste, but Skip Redirect will catch some redirects that are not initiated via a link, and make it easier to go to the original link instead.
Hope that helped you! :)
