### ISSUE TITLE
Broken on tumblr.com

### ISSUE THREAD

**Issue by Icetigris** [hyperfekt/webextension-remove-redirect#3]
Redirected links on tumblr.com don't work. Instead of going to the outbound website, they link back to the page that posted the link. 

Example redirect: http://t.umblr.com/redirect?z=https%3A%2F%2Fgithub.com%2FSDL-mirror%2FSDL&t=MmE4OGYyNmJmMGM2MzI0NmUwY2E4NDA4YjQ5NTJkNTEzYzc1MWQ5ZCxNSGJqQTZHNw%3D%3D&b=t%3ATbxQ-Whx6TMelNIYloFLTQ&p=https%3A%2F%2Ficetigris.tumblr.com%2Fpost%2F169298605761%2F2-of-365&m=0

The destination link is https://github.com/SDL-mirror/SDL
The post/page from which it was linked is https://icetigris.tumblr.com/post/169298605761/2-of-365

When the extension is enabled and I click on the link on that post, the actual destination link gets stripped out and I get directed to the page I'm already on.

**Comment by hyperfekt** [comment]
Indeed, the tumblr redirect URL scheme is incompatible since it includes both the source and the target URL. I'll look into how this could be solved without special-casing tumblr.com, but for now I recommend adding `t\.umblr\.com\/redirect` to the blacklist.

**Comment by hyperfekt** [comment]
Closing this in favor of #9, #8 and #6 which propose several orthogonal solutions to the problem.
